### ISSUE TITLE
勉強ラベル　API・モデル作成

### ISSUE THREAD

**Issue by runTech0704** [runTech0704/study_for_money#4]
## 目的

- 勉強ラベルの API・モデルを作成
- API・モデルを作成するにあたっての一連の作業内容を洗い出し、再現可能な状態にする

## ToDo
- [x] django-rest-framework の使用方法を調査
  - django にてどのように使用できるか
  - React と連携可能か？
- [x] React と django の連携
  - 方法1: React 側でビルドして、Django 内の static に含める
- [x] API の設計
- [x] モデル設計
- [x] ndb にて、モデル作成
  - ここで ndb の使い方についてよく調査する
- [x] ロジック作成
- [x] API の実装
- [x] React 側で基本的な画面の作成
- [x] React 側でビルドして、django と結合する
